root.exe -b -l -q chain.C\(666\,0\,0\)
root.exe -b -l -q chain.C\(555\,0\,0\)
root.exe -b -l -q chain.C\(0\,0\,0\)
root.exe -b -l -q chain.C\(1\,0\,0\)
root.exe -b -l -q chain.C\(-1\,0\,0\)
root.exe -b -l -q chain.C\(2\,0\,0\)
root.exe -b -l -q chain.C\(3\,0\,0\)
root.exe -b -l -q chain.C\(4\,0\,0\)
root.exe -b -l -q chain.C\(5\,0\,0\)
root.exe -b -l -q chain.C\(6\,0\,0\)
root.exe -b -l -q chain.C\(7\,0\,0\)

root.exe -b -l -q chain.C\(6661\,0\,0\)
root.exe -b -l -q chain.C\(6662\,0\,0\)
