root.exe -b -l -q chain.C\(666\,1\,0\)
root.exe -b -l -q chain.C\(555\,1\,0\)
root.exe -b -l -q chain.C\(0\,1\,0\)
root.exe -b -l -q chain.C\(1\,1\,0\)
root.exe -b -l -q chain.C\(-1\,1\,0\)
root.exe -b -l -q chain.C\(2\,1\,0\)
root.exe -b -l -q chain.C\(3\,1\,0\)
root.exe -b -l -q chain.C\(4\,1\,0\)
root.exe -b -l -q chain.C\(5\,1\,0\)
root.exe -b -l -q chain.C\(6\,1\,0\)
root.exe -b -l -q chain.C\(7\,1\,0\)

root.exe -b -l -q chain.C\(6661\,1\,0\)
root.exe -b -l -q chain.C\(6662\,1\,0\)
